cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    A12345:
      name: JohnDoe
      password: test
    B23456:
      name: AliceSmith
      password: test