[user_0]
name = "admin"
password = "password"

[user_1]
name = "admin"
password = "password"

[user_2]
name = "admin"
password = "password"

[user_3]
name = "admin"
password = "password"

[user_4]
name = "admin"
password = "password"

[user_5]
name = "admin"
password = "password"