[user_0]
name = "admin"
password = "password"

[user_1]
name = "satoshi_honda"
password = "taiyo3191"

[user_2]
name = "user000"
password = "password"

[user_3]
name = "user001"
password = "password"

[user_4]
name = "user002"
password = "password"

[user_5]
name = "user003"
password = "password"